sudo: required
services: 
  - docker

before_install: 
  - docker build -t eliranhasin1121/react-docker -f Dockerfile.dev .


script: 
  - docker run eliranhasin1121/react-docker npm run test -- --coverage